---
title: "Maping by ggplot"
author: "Jessie Xu"
date: "2021/11/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(drat)
library(hurricaneexposuredata)
library(hurricaneexposure)
library(weathermetrics)
library(geoR)
library(dplyr)
library(gstat)
library(gridExtra)
library(dplyr)
library(magrittr)
library(shiny)
library(maps)
library(geosphere)
```

```{r}
addRepo("geanders")
hurr_tracks <- hurricaneexposuredata::hurr_tracks
hurr_Humberto2007         <- hurricaneexposuredata::hurr_tracks %>% subset(storm_id == "Humberto-2007")
rain_Humberto2007         <- hurricaneexposuredata::rain %>% subset(storm_id == "Humberto-2007")
wind_Humberto2007         <- hurricaneexposuredata::storm_winds %>% subset(storm_id == "Humberto-2007")
closest_dist_Humberto2007 <- hurricaneexposuredata::closest_dist %>% subset(storm_id == "Humberto-2007")


# prepare data for ploting rainfall 
library(magrittr)
rain_Humberto2007 %<>% 
  group_by(fips) %>% 
  summarize(precip = sum(precip), precip_max = sum(precip_max),.groups = "keep")%>%
  mutate(`Rainfall(mm)` = cut(precip, 
                     breaks = c(0, 25, 50, 75, 100, 125, 150),
                     include.lowest = TRUE))%>%
  mutate(fips = as.numeric(fips)) # prepare for left_join
# rain_Humberto2007 <- na.omit(rain_Humberto2007) # check: no NA

# provide state(region) and county(subregion) based on fips
county.fips <- maps::county.fips
rain_Humberto2007 <- left_join(rain_Humberto2007, county.fips, by = "fips")
rain_Humberto2007 %<>% 
  separate(polyname, c("region", "subregion"), sep = ",")
# provide longitude and latitude 
# unique(rain_Humberto2007$state)
region <- c("alabama", "arkansas", "connecticut", "delaware", "district of columbia",
                "florida","georgia", "illinois", "indiana","iowa", 
                "kansas", "kentucky", "louisiana","maine", "maryland",
                "massachusetts", "michigan", "mississippi", "missouri","new hampshire", 
                "new jersey", "new york", "north carolina", "ohio", "oklahoma", 
                "pennsylvania", "rhode island", "south carolina","tennessee", "texas",
                "vermont","virginia", "west virginia", "wisconsin")  
counties <- map_data(map = "county", region = region)
state    <- map_data(map = "state", region = region)
rain_Humberto2007 <- left_join(rain_Humberto2007, counties, 
                               by = c("region", "subregion"))

```

```{r}
# plot rainfall
plot_rainfall <-
  ggplot() + 
  geom_polygon(data = rain_Humberto2007, 
               aes(x = long, y = lat, group = group,fill = `Rainfall(mm)`), 
               color = "grey", size = 0.2, alpha = 1.6) + 
  geom_polygon(data = state, aes(x = long, y = lat, group = group),
               color="black", fill="white", size = 0.2, alpha = 0.3) +
  geom_path(aes(x = hurr_Humberto2007$longitude, y = hurr_Humberto2007$latitude), color = "red4") +
  scale_fill_brewer(palette = "Blues") +
  ggtitle("Humberto-2007") +
  theme(plot.title=element_text(hjust=0.5),
        panel.background=element_blank(),
        panel.border=element_blank(),
        axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())
# 42019 Location: 27.910N 95.345W
# 42035 Location: 29.232N 94.413W
# SRST2 Location: 29.683N 94.033W

y <- c(27.910, 29.232, 29.683) 
x <- c(-95.345, -94.413, -94.033)
bouys_location <- data.frame(x,y)

plot_rainfall <- 
  plot_rainfall+
  geom_point(data = bouys_location, aes(x=x,y=y), size = 2, shape = 23,  fill = "yellow")
plot_rainfall

# plot exposure
rain_Humberto2007$scale <- cut(rain_Humberto2007$precip,c(-1,100,500),c("Unexposed","Exposed"),ordered_result = T)
plot_exposure <- 
  ggplot()+
  geom_polygon(data = rain_Humberto2007, 
               aes(x = long, y = lat, group = group, fill = scale), 
               color = "grey", size = 0.2, alpha = 1.6) + 
  geom_polygon(data = state, aes(x = long, y = lat, group = group),
               color="black", fill="white", size = 0.2, alpha = 0.3) +
  geom_path(aes(x = hurr_Humberto2007$longitude, y = hurr_Humberto2007$latitude), color = "red4") +
  ggtitle("Humberto-2007") +
  theme(plot.title=element_text(hjust=0.5),
        panel.background=element_blank(),
        panel.border=element_blank(),
        axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())+
  scale_fill_manual("Rain > 100 mm",values=c("white","darkblue"))
plot_exposure
```

```{r}
plot1 <- plot_Humberto2007$rmap
plot2 <- plot_Humberto2007$wmap
plot3 <- plot_Humberto2007$expos

# plot1 +geom_point(data = bouys_location, aes(x=x,y=y), size = 2, shape = 23,  fill = "yellow")

# 42019 Location: 27.910N 95.345W
# 42035 Location: 29.232N 94.413W
# SRST2 Location: 29.683N 94.033W

# WSPD
raw_42019   <- dt_42019 %>% select(date_time, WSPD) %>% 
  add_column(buoy = rep("buoy_42019", length(dt_42019$date_time)), .after = 0)
colnames(raw_42019)[3] <- c("average_wind_speed")
raw_42019$average_wind_speed <- as.numeric(raw_42019$average_wind_speed)

# summarise daily data(buoy_42035)
raw_42035   <- dt_42035 %>% select(date_time, WSPD) %>% 
  add_column(buoy = rep("buoy_42035", length(dt_42035$date_time)), .after = 0)
colnames(raw_42035)[3] <- c("average_wind_speed")
raw_42035$average_wind_speed <- as.numeric(raw_42035$average_wind_speed)


# summarise daily data(buoy_srst2)
raw_srst2   <- dt_srst2 %>% select(date_time, WSPD) %>% 
  add_column(buoy = rep("buoy_srst2", length(dt_srst2$date_time)), .after = 0)
colnames(raw_srst2)[3] <- c("average_wind_speed")
raw_srst2$average_wind_speed <- as.numeric(raw_srst2$average_wind_speed )


# put them into one Dataframee
buoy_raw <- rbind(raw_42019, raw_42035, raw_srst2)
buoy_location <- data.frame(buoy = unique(buoy_daily$buoy), 
                            longitude  = bouys_location$x, 
                            latitude   = bouys_location$y)
buoy_raw <- buoy_raw %>% inner_join(buoy_location, by = "buoy")

# unique(buoy_daily$date_time)
# plot1 +geom_point(data = bouys_location, aes(x=x,y=y), size = 2, shape = 23,  fill = "yellow")
# plot1 +geom_point(data = unique(select(buoy_raw, buoy, longitude, latitude)), aes(x = longitude,y = latitude),  size = 2, shape = 23,  fill = "yellow")
```

```{r}
# ggplot(buoy_raw) + 
#   geom_line(aes(x = date_time, y = average_wind_speed, color = buoy))
# calculate Haversine distance
hurr_Humberto2007 %<>% mutate(dist_42019 = NA, dist_42035 = NA, dist_srst2 = NA)
for(i in 1:  dim(hurr_Humberto2007)[1]){
  hurr_Humberto2007$dist_42019[i] <- distHaversine(c(hurr_Humberto2007$longitude[i], hurr_Humberto2007$latitude[i]), 
                                                   c(buoy_location$longitude[1], buoy_location$latitude[1]), r=6378137)
  hurr_Humberto2007$dist_42035[i] <- distHaversine(c(hurr_Humberto2007$longitude[i], hurr_Humberto2007$latitude[i]),
                                                   c(buoy_location$longitude[2], buoy_location$latitude[2]), r=6378137)
  hurr_Humberto2007$dist_srst2[i] <- distHaversine(c(hurr_Humberto2007$longitude[i], hurr_Humberto2007$latitude[i]),
                                                   c(buoy_location$longitude[3], buoy_location$latitude[3]), r=6378137)
}
buoy_location %<>% mutate(closest_date = rep(NA, dim(buoy_location)[1]))
# set the closest_date
buoy_location$closest_date[1] <- hurr_Humberto2007$date[which(hurr_Humberto2007$dist_42019 == min(hurr_Humberto2007$dist_42019))] 
buoy_location$closest_date[2] <- hurr_Humberto2007$date[which(hurr_Humberto2007$dist_42035 == min(hurr_Humberto2007$dist_42035))] 
buoy_location$closest_date[3] <- hurr_Humberto2007$date[which(hurr_Humberto2007$dist_srst2 == min(hurr_Humberto2007$dist_srst2))] 
buoy_location$closest_date <- lubridate::ymd_hm(buoy_location$closest_date)

ggplot(subset(buoy_raw, buoy == "buoy_42019"), aes(x = date_time, y = average_wind_speed)) + 
  geom_line() + 
  geom_rect(aes(xmin=(buoy_location$closest_date[1] - 1*60*60*24), 
                xmax=(buoy_location$closest_date[1] + 1*60*60*24),
                ymin=0, ymax=Inf), alpha = .01, fill = "#9898fb") + 
  xlab("Time") + ylab("Average wind speed(hourly)") + theme_bw()

ggplot(subset(buoy_raw, buoy == "buoy_42035"), aes(x = date_time, y = average_wind_speed)) + 
  geom_line() + 
  geom_rect(aes(xmin=(buoy_location$closest_date[2] - 1*60*60*24), 
                xmax=(buoy_location$closest_date[2] + 1*60*60*24),
                ymin=0, ymax=Inf), alpha = .01, fill = "#9898fb") + 
  xlab("Time") + ylab("Average wind speed(hourly)") + theme_bw()

ggplot(subset(buoy_raw, buoy == "buoy_srst2"), aes(x = date_time, y = average_wind_speed)) + 
  geom_line() + 
  geom_rect(aes(xmin=(buoy_location$closest_date[3] - 1*60*60*24), 
                xmax=(buoy_location$closest_date[3] + 1*60*60*24),
                ymin=0, ymax=Inf), alpha = .01, fill = "#9898fb") + 
  xlab("Time") + ylab("Average wind speed(hourly)") + theme_bw()

```
