---
title: "variogram_hmapper"
author: "shuting"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(drat)
library(hurricaneexposuredata)
library(hurricaneexposure)
library(weathermetrics)
library(geoR)
library(dplyr)
install.packages("OSMscale")
library(OSMscale)
```

## convert latitude & longitude to 2D distance
```{r}
latlongtProjection <- projectPoints(latitude, longitude, expo_wind)
latlongtProjection$fips <- expo_wind$fips
latlongtProjection$storm_id <- expo_wind$storm_id
expo_wind_new <- merge(expo_wind,latlongtProjection,by=c("fips","storm_id"))
#dists <- dist(expo_wind_new[,11:12])
```
From package "OSMscale".

Function description: Project long lat points to e.g. UTM projection. 

Link: https://cran.r-project.org/web/packages/OSMscale/OSMscale.pdf


## variogram
```{r}
coordinates(expo_wind_new) <- ~ x + y
v_windVmaxGust <- variogram(vmax_gust~1, expo_wind_new) ##dataset becomes small, why?

ggplot(v_windVmaxGust)+
  geom_point(aes(x=dist,y=gamma))
v_windVmaxGust_fit <- fit.variogram(v_windVmaxGust, vgm("Sph", 700))
```

